# Generated by Django 3.2.23 on 2024-01-19 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menus',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
