# Generated by Django 3.2.23 on 2024-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.FloatField(default=1000),
        ),
    ]
