# Generated by Django 3.2.23 on 2024-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
