# Generated by Django 3.2.23 on 2024-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240118_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_restaurant_owner',
            field=models.BooleanField(default=False),
        ),
    ]
