# Generated by Django 3.2.23 on 2024-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='street_address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
