# Generated by Django 3.2.23 on 2024-01-20 18:09

import django.core.validators
from django.db import migrations, models


def add_phone_numbers(apps, schema_editor):
    Users = apps.get_model("users", "Users")

    for i, user in enumerate(Users.objects.all()):
        user.phone_number = f"{i:010d}"
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_users_street_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="phone_number",
            field=models.CharField(
                error_messages={"unique": "This phone number is already in use."},
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Please enter valid 10 digits number.", regex="^\\d{10}$"
                    )
                ],
            ),
        ),
        migrations.RunPython(add_phone_numbers),
    ]
